name: example
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  pgsql_annotation: ^4.0.0

dev_dependencies:
  build_runner: ^1.0.0

  # Used by tests. Not required to use `pgsql_serializable`.
  build_verify: ^1.0.0

  pgsql_serializable: ^4.0.0

  # Used by tests. Not required to use `pgsql_serializable`.
  path: ^1.8.0
  # Used by tests. Not required to use `pgsql_serializable`.
  test: ^1.16.0
