name: example

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  pgsql_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^1.0.0
  pgsql_serializable: ^3.2.0

  # Used by tests. Not required to use `json_serializable`.
  build_verify: ^1.0.0
  path: ^1.5.1
  test: ^1.6.0

dependency_overrides:
  pgsql_annotation:
    path: ../pgsql_annotation
  pgsql_serializable:
    path: ../pgsql_serializable
