name: example
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  pgsql_annotation: ^4.3.0

dev_dependencies:
  build_runner: ^2.0.0

  # Used by tests. Not required to use `pgsql_serializable`.
  build_verify: ^2.0.0

  pgsql_serializable: ^6.0.0

  # Used by tests. Not required to use `pgsql_serializable`.
  path: ^1.8.0
  # Used by tests. Not required to use `pgsql_serializable`.
  test: ^1.16.0
