name: example
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  pgsql_annotation: ^4.8.0

dev_dependencies:
  # Used by tests. Not required to use `pgsql_serializable`.
  _pgsql_serial_shared_test:
    path: ../shared_test

  # REQUIRED!
  build_runner: ^2.3.3

  # Used by tests. Not required to use `pgsql_serializable`.
  build_verify: ^3.0.0

  # REQUIRED!
  pgsql_serializable: ^6.6.0

  # Not required to use `pgsql_serializable`.
  lints: ^2.0.0
  path: ^1.8.0
  test: ^1.16.0

# This section is used to verify changes to these packages. Do not include in
# your code!
dependency_overrides:
  pgsql_annotation:
    path: ../pgsql_annotation
  pgsql_serializable:
    path: ../pgsql_serializable
