name: pgsql_annotation
version: 4.0.1
description: >-
  Classes and helper functions that support PgSQL code generation via the
  `pgsql_serializable` package.
repository: https://github.com/anycode/pgsql_serializable.dart
environment:
  sdk: '>=2.12.0 <3.0.0'

# When changing PgSqlSerializable class.
# dev_dependencies:
#   build_runner: ^1.0.0
#   pgsql_serializable: ^4.0.0
