name: pgsql_annotation
version: 4.8.0
description: >-
  Classes and helper functions that support PgSQL code generation via the
  `pgsql_serializable` package.
repository: https://github.com/google/pgsql_serializable.dart/tree/master/pgsql_annotation

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  meta: ^1.9.1

dev_dependencies:
  lints: ^2.0.1
# When changing PgSqlSerializable class.
#  build_runner: ^2.0.0
#  pgsql_serializable: any
