name: pgsql_annotation
version: 4.6.0
description: >-
  Classes and helper functions that support PgSQL code generation via the
  `pgsql_serializable` package.
repository: https://github.com/google/pgsql_serializable.dart/tree/master/pgsql_annotation

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  meta: ^1.4.0

# When changing PgSqlSerializable class.
# dev_dependencies:
#  build_runner: ^2.0.0
#  pgsql_serializable: any
