name: pgsql_serializable
version: 6.6.1
description: >-
  Automatically generate code for converting to and from PgSQL by annotating
  Dart classes.
repository: https://github.com/anycode/pgsql_serializable.dart/tree/master/pgsql_serializable
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  analyzer: ^5.11.1
  async: ^2.11.0
  build: ^2.3.1
  build_config: '>=0.4.4 <2.0.0'
  collection: ^1.17.1
  meta: ^1.9.1
  path: ^1.8.3

  # Use a tight version constraint to ensure that a constraint on
  # `pgsql_annotation` properly constrains all features it provides.
  pgsql_annotation: '>=4.8.0 <4.9.0'
  pub_semver: ^2.1.3
  pubspec_parse: ^1.2.2
  source_gen: ^1.2.7
  source_helper: ^1.3.3

dev_dependencies:
  _pgsql_serial_shared_test:
    path: ../shared_test
  build_runner: ^2.3.3
  build_verify: ^3.1.0
  dart_style: ^2.3.0
  lints: ^2.0.1
  logging: ^1.1.1
  source_gen_test: ^1.0.4
  test: ^1.24.2
  test_descriptor: ^2.0.1
  test_process: ^2.0.3
  yaml: ^3.1.1

dependency_overrides:
  pgsql_annotation:
    #path: ../pgsql_annotation
    git:
      url: git@github.com:anycode/pgsql_serializable.dart.git
      ref: pgsql_annotation-v4.8.0
      path: pgsql_annotation
