name: pgsql_serializable
version: 6.0.1
description: >-
  Automatically generate code for converting to and from PgSql by annotating
  Dart classes.
repository: https://github.com/google/pgsql_serializable.dart/tree/master/pgsql_serializable
environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  analyzer: ^2.0.0
  async: ^2.8.0
  build: ^2.0.0
  build_config: '>=0.4.4 <2.0.0'
  collection: ^1.14.0

  # Use a tight version constraint to ensure that a constraint on
  # `pgsql_annotation` properly constrains all features it provides.
  pgsql_annotation: #'>=4.3.0 <4.4.0'
    #path: ../pgsql_annotation
    git:
      url: git@github.com:anycode/pgsql_serializable.dart.git
      ref: pgsql_annotation-v4.3.0
      path: pgsql_annotation
  meta: ^1.3.0
  path: ^1.8.0
  pub_semver: ^2.0.0
  pubspec_parse: ^1.0.0
  source_gen: ^1.0.0
  source_helper: ^1.3.0

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^2.0.0
  dart_style: ^2.0.0
  logging: ^1.0.0
  source_gen_test: ^1.0.0
  stack_trace: ^1.10.0
  test: ^1.16.0
  test_descriptor: ^2.0.0
  test_process: ^2.0.0
  yaml: ^3.0.0
