name: pgsql_serializable
version: 6.1.6
description: >-
  Automatically generate code for converting to and from PgSQL by annotating
  Dart classes.
repository: https://github.com/anycode/pgsql_serializable.dart/tree/main/pgsql_serializable
environment:
  sdk: '>=2.14.0 <3.0.0'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

dependencies:
  analyzer: '>=2.0.0 <5.0.0'
  async: ^2.9.0
  build: ^2.3.0
  build_config: '>=0.4.4 <2.0.0'
  collection: ^1.16.0

  # Use a tight version constraint to ensure that a constraint on
  # `pgsql_annotation` properly constrains all features it provides.
  pgsql_annotation: #'>=4.4.0 <4.5.0'
    #path: ../pgsql_annotation
    git:
      url: git@github.com:anycode/pgsql_serializable.dart.git
      ref: pgsql_annotation-v4.4.0
      path: pgsql_annotation
  meta: ^1.7.0
  path: ^1.8.1
  pub_semver: ^2.1.1
  pubspec_parse: ^1.2.0
  source_gen: ^1.2.2
  source_helper: ^1.3.2

dev_dependencies:
  _pgsql_serial_shared_test:
    path: ../shared_test
  build_runner: ^2.1.10
  build_verify: ^3.0.0
  dart_style: ^2.2.3
  logging: ^1.0.2
  source_gen_test: ^1.0.3
  test: ^1.21.0
  test_descriptor: ^2.0.0
  test_process: ^2.0.2
  yaml: ^3.1.0
