name: pgsql_serializable
version: 4.1.0
description: >-
  Automatically generate code for converting to and from PgSQL by annotating
  Dart classes.
repository: https://github.com/anycode/pgsql_serializable.dart/tree/master/pgsql_serializable
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: '>=0.41.2 <2.0.0'
  build: ^2.0.0
  build_config: ^0.4.7
  collection: ^1.15.0

  # Use a tight version constraint to ensure that a constraint on
  # `pgsql_annotation` properly constrains all features it provides.
  # For v3 only – allow a wide range since the only change was to REMOVE things
  # from pgsql_annotation
  #pgsql_annotation: '>=4.0.0 <4.1.0'
  pgsql_annotation:
    path: ../pgsql_annotation
  #  git:
  #    url: git@github.com:anycode/pgsql_serializable.dart.git
  #    ref: pgsql_annotation-v4.0.0
  #    path: pgsql_annotation
  meta: ^1.3.0
  path: ^1.8.0
  source_gen: ^1.0.0

dev_dependencies:
  build_runner: ^1.12.2
  build_verify: ^2.0.0
  dart_style: ^2.0.0
  logging: ^1.0.0
  pub_semver: ^2.0.0
  source_gen_test: ^1.0.0
  stack_trace: ^1.10.0
  test: ^1.16.8
  yaml: ^3.1.0
