name: _test_yaml
publish_to: none

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.0.0
  build_verify: ^1.1.0
  test: ^1.6.0

  # Repo packages
  checked_yaml: any
  pgsql_annotation: any
  pgsql_serializable: any

dependency_overrides:
  checked_yaml:
    path: ../checked_yaml
  pgsql_annotation:
    path: ../pgsql_annotation
  pgsql_serializable:
    path: ../pgsql_serializable
