name: _test_yaml
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  checked_yaml: any
  pgsql_annotation: ^4.4.0
  pgsql_serializable: any
  test: ^1.6.0
  yaml: ^3.0.0

dependency_overrides:
  checked_yaml:
    path: ../checked_yaml
  pgsql_annotation:
    path: ../pgsql_annotation
  pgsql_serializable:
    path: ../pgsql_serializable
