name: checked_yaml
version: 2.0.4-wip

description: >-
  Generate more helpful exceptions when decoding YAML documents using
  package:pgsql_serializable and package:yaml.
repository: https://github.com/anycode/pgsql_serializable.dart/tree/master/checked_yaml
topics:
 - yaml
 - pgsql
 - build-runner
 - pgsql-serializable
 - codegen

environment:
  sdk: ^3.0.0

dependencies:
  pgsql_annotation: ^4.3.0
  source_span: ^1.8.0
  yaml: ^3.0.0

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  dart_flutter_team_lints: ^2.0.0
  pgsql_serializable: ^6.0.0
  path: ^1.0.0
  test: ^1.16.0
  test_process: ^2.0.0

#dependency_overrides:
#  pgsql_annotation:
#    path: ../pgsql_annotation
#  pgsql_serializable:
#    path: ../pgsql_serializable
